title: Madhavi Nithianandam
logo: "/images/profile_pic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  AI Engineer with 1+ years of experience in AI/ML development and data analytics, skilled in data preprocessing and visualization, model design and training, optimization, and model evaluation. 

  
  Earned AI certification from Case Western Reserve University
  <br><br>
  <a href="https://www.linkedin.com/in/madhavi-nithianandam/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

