title: Madhavi Nithianandam
logo: "/images/profile_pic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Senior Analyst with 1+ years of experience in data analytics, data preprocessing and visualization, model design and training, optimization, and model evaluation.
  Leveraging over 11 years in IT and 7 years in QA leadership, I combine analytical thinking and technical expertise to build data-driven and AI-powered solutions that enhance business decision-making.
  
  <br><br>  
  Earned AI certification from Case Western Reserve University
  <br><br>
  <a href="https://www.linkedin.com/in/madhavi-nithianandam/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

